version: 2.1

_run:
  up-containers: &up-containers
    name: 'Up containers'
    command: |
      echo "MAGENTO_VERSION=$MAGENTO_VERSION" >> .env
      echo "IMGUR_CLIENT_ID=$IMGUR_CLIENT_ID" >> .env
      make up-containers
  composer-install: &composer-install
    name: 'Install dependencies'
    command: 'make composer-install'

jobs:
  checkout-code:
    machine:
      enabled: true
    steps:
      - checkout
      - persist_to_workspace:
            root: ~/project
            paths:
              - ./

  install-dependencies:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install composer dependencies
          command: make composer-install
      - persist_to_workspace:
            root: ~/project
            paths:
              - ./

  forgotten-keys:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: 'Avoid forgotten keys'
          command: 'make check-forgotten-keys'

  unit:
    description: Parameterized job to run unit tests
    parameters:
      magento_version:
        description: "Magento version to be used"
        type: string
        default: "1.8.1.0"
    machine:
      enabled: true
    environment:
      MAGENTO_VERSION: << parameters.magento_version >>
    steps:
      - attach_workspace:
          at: ~/project
      - run: *up-containers
      - run:
          name: 'Running unit tests against magento << parameters.magento_version >>'
          command: 'make test-unit'

  end-to-end:
    description: Parameterized job to run end-to-end suites
    parameters:
      suite_name:
        description: "the suite name to be ran"
        type: string
      magento_version:
        description: "Magento version to be used"
        type: string
        default: "1.8.1.0"
      before-deps:
        description: "Steps that should be run before the test suite"
        type: steps
        default: []
    machine:
      enabled: true
    environment:
      MAGENTO_VERSION: << parameters.magento_version >>
    steps:
      - attach_workspace:
          at: ~/project
      - run: *up-containers
      - steps: << parameters.before-deps >>
      - run:
          name: Running << parameters.suite_name >> end to end suite test
          command: make test-e2e-suite suite=<< parameters.suite_name >>
      - run:
          name: Show magento's system and error logs
          when: on_fail
          command: |
            make show-system-logs
            make show-exception-logs

  build-release-artifact:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Build artifact to be released"
          command: |
            chmod +x ~/project/script/build-artifact.sh
            make build-release-artifact RELEASE_TAG=${CIRCLE_TAG}
      - persist_to_workspace:
          root: ~/project
          paths:
              - ./

  publish-release-github:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Publish Release on Github"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./build/

workflows:
  version: 2
  release:
    jobs:
      - checkout-code:
          filters:
            tags:
              only: /^v.*$/
      - build-release-artifact:
          requires:
          - checkout-code
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-release-github:
          requires:
            - build-release-artifact
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
  tests:
    jobs:
      - checkout-code
      - forgotten-keys:
          requires:
          - checkout-code
      - install-dependencies:
          requires:
          - checkout-code
      - unit:
          name: unit-mage-1.7
          magento_version: "1.7.0.2"
          requires:
            - forgotten-keys
            - install-dependencies
      - unit:
          name: unit-mage-1.8
          magento_version: "1.8.1.0"
          requires:
            - forgotten-keys
            - install-dependencies
      - unit:
          name: unit-mage-1.9
          magento_version: "1.9.1.0"
          requires:
            - forgotten-keys
            - install-dependencies
      - end-to-end:
          name: e2e-configure-mage-1.8
          suite_name: "configure"
          magento_version: "1.8.1.0"
          requires:
            - unit-mage-1.8
      - end-to-end:
          name: e2e-credit_card-mage-1.8
          suite_name: "credit_card"
          magento_version: "1.8.1.0"
          requires:
            - unit-mage-1.8
      - end-to-end:
          name: e2e-boleto-mage-1.8
          suite_name: "boleto"
          magento_version: "1.8.1.0"
          requires:
            - unit-mage-1.8
      - end-to-end:
          name: e2e-postback-mage-1.8
          suite_name: "postback"
          magento_version: "1.8.1.0"
          before-deps:
            - run: make test-e2e-suite suite=configure
          requires:
            - unit-mage-1.8
      - end-to-end:
          name: e2e-configure-mage-1.7
          suite_name: "configure"
          magento_version: "1.7.0.2"
          requires:
            - unit-mage-1.7
      - end-to-end:
          name: e2e-credit_card-mage-1.7
          suite_name: "credit_card"
          magento_version: "1.7.0.2"
          requires:
            - unit-mage-1.7
      - end-to-end:
          name: e2e-boleto-mage-1.7
          suite_name: "boleto"
          magento_version: "1.7.0.2"
          requires:
            - unit-mage-1.7
      - end-to-end:
          name: e2e-postback-mage-1.7
          suite_name: "postback"
          magento_version: "1.7.0.2"
          before-deps:
            - run: make test-e2e-suite suite=configure
          requires:
            - unit-mage-1.7
      - end-to-end:
          name: e2e-configure-mage-1.9
          suite_name: "configure"
          magento_version: "1.9.1.0"
          requires:
            - unit-mage-1.9
      - end-to-end:
          name: e2e-credit_card-mage-1.9
          suite_name: "credit_card"
          magento_version: "1.9.1.0"
          requires:
            - unit-mage-1.9
      - end-to-end:
          name: e2e-boleto-mage-1.9
          suite_name: "boleto"
          magento_version: "1.9.1.0"
          requires:
            - unit-mage-1.9
      - end-to-end:
          name: e2e-postback-mage-1.9
          suite_name: "postback"
          magento_version: "1.9.1.0"
          before-deps:
            - run: make test-e2e-suite suite=configure
          requires:
            - unit-mage-1.9